name: Test deploy github deploy via FTP

run-name: FCS Wordpress GitHub Actions 🚀
on:
  push:
    branches:
      - shin
      - main

jobs:
  web-deploy-via-sfpt:
    name: 🚀 Deploy Website Every Commit

    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: 📂 Sync Files
        uses: easingthemes/ssh-deploy@main

        with:
          REMOTE_HOST: 82.180.152.249
          REMOTE_USER: u796998893
          SSH_PRIVATE_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5yyFtbQOMM1YaMMUA5EmU0FxY4p2+HD5ulTGIdLXO2Sej2bVEOOnR33XdllYX42+bA0wSjr13gFv2UtOW/V93ayvxv8d9BiNKuvQKJdDmslN5l3bY96HvALop2UaPnc0MthtR/dSI7jzAymyWkQ1zszJcHyJpNrVrOL9UR/xVh0+liHDzGnLV2V93FqXGKHksj5jZLQX5iGwnGV3LL+XockJvPnvLfQnWKqfLkOCL1zvT8gmfFqlTVsyYT8xsL0rDpwalqVIx3obdw7QuvgMmMpcoVseCIPaKdi9qXLfhZ7anSsPf1l/XpDuxQjt14AqP6tUozUbdx/qrW6d6Zh8/uobY8NKiIb6Q46OTZ3A7wmuyeAvpI1LU+QPFKdmdv5uLGcDcNYJhOLRaplF7v+XUMWC5LzzSlGCNL3uhlkGwDlhLMawQ2BU+yCSesOPSMmnSU5JUwnh/QZHV1msdrvk7etQE0c5Vtd8iNgR9CwvLktjkYXnFKGsOpYA5uzGSfs9MjwAdFwHyRCCxi2OdbA8eSKWeUtazEUm+oo31eh4Sa84iDbiZvZCGRiyCuhyhqyGsASnyfgqAvs7A6Gj7S1ixXGbYCQ/ZIbQ7o2mqQpfwFZpDdc0aHkBy3FI0zMc5HgkKSD/hMd8HG0MPRM9omPyR7Okl0DW6CwqY92PnhYNs0w== shin@shin-ThinkPad-E15-Gen-3
          REMOTE_PORT: 65002
          SOURCE: ~/public_html/shin/
          EXCLUDE: "/dist/, /node_modules/"
