name: Test deploy github deploy via FTP

run-name: FCS Wordpress GitHub Actions 🚀
on:
  push:
    branches:
      # - shin
      - main

jobs:
  web-deploy-via-sfpt:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3
        
      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1

        with:
          target-server: 82.180.152.249
          remote-user: u796998893
          private-ssh-key: ${{ secrets.SSH_KEY }}
          ssh-port: 65002
          destination-path: ~/public_html/shin/

